[tools]
node = "20"

[settings]
plugin_autoupdate_last_check_duration = '1 week'
verbose = false
not_found_auto_install = true
experimental = true
status = { missing_tools = "always", show_env = false, show_tools = false }
